### ISSUE TITLE
TPU Calculation not running v2.2.0

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/cBLUE.github.io#37]
When running cBLUE  v2.2.0, trajectory loads fine but when we press the button to calculate TPU it finishes quickly with no files created.

![image](https://user-images.githubusercontent.com/35336539/77010561-3f9b3a00-6927-11ea-8c7f-8aab92a352ae.png)

Also noticed the cBLUE_version in the configuration json is indicating v2.1.1 along with the splash screen and Help --> About

**Comment by forkozi** [comment]
this was due to me accidentally leaving in a chunk of troubleshooting code; fixed
