### ISSUE TITLE
las.py | ValueError: no field of name raw_classification

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/cBLUE.github.io#39]
Some las files fail when trying to process TPU if they are not "raw_classification" type.

Workaround currently is to change in las.py 
line 104
from
        _c = self.points_to_process['raw classification']_
to 
        _c = self.points_to_process['classification_byte']_

**Comment by jkspring** [comment]
Looks to be a las 1.2 vs. las 1.4 issue.

**Comment by forkozi** [comment]
Thanks.  This should be an easy one.  I'll add an if/then to decide what key to use based on the las version.

**Comment by klangrjt** [comment]
Fixed in commit [844ac87e6cf3f5c8b42bb9e0632aa0fd88e5313a](https://github.com/noaa-rsd/cBLUE.github.io/tree/844ac87e6cf3f5c8b42bb9e0632aa0fd88e5313a)
