### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/cBLUE.github.io#44]
Hi,

I am re-running cBLUE on FL1606 and FL1607 since they are the only two so far (other than FL1604 which was already submitted to MCD) with the pointID zero issue (TUV/THU tile issue) and I am seeing the following error:
![image](https://user-images.githubusercontent.com/44785008/103421371-f476ae80-4b69-11eb-94c5-e4fc6941c494.png)

For FL1606 I used the following las files:  \\ngs-s-rsd\Lidar_Proc\2017\FL1606-TB-N-880_DeSoto_to_BocaGrande_p\FL1606-TB-N-880_DeSoto_to_BocaGrande_02_p\06_RIEGL_PROC\04_EXPORT\Green\05_FL1606_DeSoto_Sarasota_02_g_gpsa_rf_ip_wsf_r_tm_qc_geocode\las_1.4_domain

SBET directory:   \\ngs-s-rsd\Lidar_Proc\2017\FL1606-TB-N-880_DeSoto_to_BocaGrande_p\tpu_sbet

Are these correct? wondering if either of these are causing a problem.

Also, I used the following parameters from the .json file as Jamie suggested:
 "water surface": "Model (ECKV spectrum)",
 "wind": "Gentle Breeze (7-10 kts)",
 "kd": "Moderate (0.18-0.25 m^-1)",
 "VDatum region": "---No Region Specified---",
"water_surface_ellipsoid_height": -24.3

Thanks for any assistance,
g

**Comment by gimahori** [comment]
sorry for some reason I hit something and two issues were created - so I deleted one -apologies if that caused confusion.
this one has the completed issue with the parameters listed.
thx,
g

**Comment by klangrjt** [comment]
I'll look into this today and get back to you.

Thanks,

-Rudy

**Comment by klangrjt** [comment]
Just pushed an update that resolves this issue.
When you first start cBlue the MCU region is now properly initiallized to no mcu region.
You no longer have to select then reselect the option in the drop down menu.
